version: '3.8'

services:
  web:
    build: .
    command: >
      sh -c "cd tableandgo &&
             python -c \"import time; time.sleep(30)\" &&
             python manage.py migrate &&
             python manage.py init_data &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - SECRET_KEY=django-insecure-123
      - POSTGRES_DB=table_and_go
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1019
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - IN_DOCKER=1
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app_network
    restart: on-failure

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=table_and_go
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1019
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    ports:
      - "5432:5432"
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge
