# Generated by Django 5.1.7 on 2025-04-07 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
    ]
