# Generated by Django 5.1.7 on 2025-03-30 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_system_admin',
            field=models.BooleanField(default=False, verbose_name='Администратор системы'),
        ),
    ]
