# Generated by Django 5.1.6 on 2025-04-06 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название филиала')),
                ('is_main', models.BooleanField(default=False, verbose_name='Основной филиал')),
                ('address', models.CharField(max_length=256, verbose_name='Адрес филиала')),
                ('phone', models.CharField(max_length=10, verbose_name='Номер телефона')),
                ('average_check', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Средний чек')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Филиал',
                'verbose_name_plural': 'Филиалы',
                'ordering': ['establishment', '-is_main', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Кухня',
                'verbose_name_plural': 'Кухни',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название района')),
            ],
            options={
                'verbose_name': 'Район',
                'verbose_name_plural': 'Районы',
            },
        ),
        migrations.CreateModel(
            name='BranchImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='branch_images', verbose_name='Фото филиала')),
                ('caption', models.CharField(blank=True, max_length=150, null=True, verbose_name='Описание фото')),
                ('is_main', models.BooleanField(default=False, verbose_name='Главное изображение')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='restaurants.branch', verbose_name='Филиал')),
            ],
            options={
                'verbose_name': 'Фото филиала',
                'verbose_name_plural': 'Фото филиалов',
                'ordering': ['-is_main', 'order'],
            },
        ),
        migrations.AddField(
            model_name='branch',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='restaurants.district', verbose_name='Район'),
        ),
        migrations.CreateModel(
            name='Establishment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('establishment_type', models.CharField(choices=[('bar', 'Бар'), ('restaurant', 'Ресторан')], default='restaurant', max_length=20, verbose_name='Тип заведения')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название заведения')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание заведения')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('website_url', models.URLField(blank=True, null=True, verbose_name='Сайт ресторана')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('cuisines', models.ManyToManyField(related_name='restaurants', to='restaurants.cuisine', verbose_name='Типы кухни')),
            ],
            options={
                'verbose_name': 'Заведение',
                'verbose_name_plural': 'Заведения',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='branch',
            name='establishment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='restaurants.establishment', verbose_name='Заведение'),
        ),
        migrations.CreateModel(
            name='AdminInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email приглашаемого')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Телефон приглашаемого')),
                ('invitation_code', models.CharField(max_length=20, unique=True, verbose_name='Код приглашения')),
                ('is_used', models.BooleanField(default=False, verbose_name='Использовано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('expires_at', models.DateTimeField(verbose_name='Действительно до')),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='restaurants.establishment', verbose_name='Ресторан')),
            ],
            options={
                'verbose_name': 'Приглашение администратора',
                'verbose_name_plural': 'Приглашения администраторов',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название блюда')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('category', models.CharField(choices=[('starter', 'Закуска'), ('main', 'Основное блюдо'), ('dessert', 'Десерт'), ('drink', 'Напиток'), ('salad', 'Салат')], max_length=30, verbose_name='Категория')),
                ('image', models.ImageField(blank=True, null=True, upload_to='menu/', verbose_name='Фото блюда')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступно')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu', to='restaurants.branch', verbose_name='Филиал')),
            ],
            options={
                'verbose_name': 'Пункты меню',
                'verbose_name_plural': 'Пункты меню',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='branch',
            unique_together={('establishment', 'name')},
        ),
        migrations.CreateModel(
            name='EstablishmentAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('establishment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='administrators', to='restaurants.establishment', verbose_name='Заведение')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_admin_roles', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Администратор ресторана',
                'verbose_name_plural': 'Администраторы ресторанов',
                'unique_together': {('user', 'establishment')},
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Номер столика')),
                ('capacity', models.IntegerField(verbose_name='Вместимость')),
                ('status', models.CharField(choices=[('available', 'Доступен'), ('reserved', 'Забронирован'), ('maintenance', 'На обслуживании')], default='available', max_length=50, verbose_name='Статус')),
                ('location', models.CharField(blank=True, max_length=100, null=True, verbose_name='Расположение')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='restaurants.branch', verbose_name='Ресторан')),
            ],
            options={
                'verbose_name': 'Столик',
                'verbose_name_plural': 'Столики',
                'ordering': ['branch', 'number'],
                'unique_together': {('branch', 'number')},
            },
        ),
        migrations.CreateModel(
            name='WorkingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Суббота'), (6, 'Воскресенье')], verbose_name='День недели')),
                ('opening_time', models.TimeField(blank=True, null=True, verbose_name='Время открытия')),
                ('closing_time', models.TimeField(blank=True, null=True, verbose_name='Время закрытия')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Выходной')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='working_hours', to='restaurants.branch', verbose_name='Ресторан')),
            ],
            options={
                'verbose_name': 'Часы работы',
                'verbose_name_plural': 'Часы работы',
                'ordering': ['branch', 'day_of_week'],
                'unique_together': {('branch', 'day_of_week')},
            },
        ),
    ]
