# Generated by Django 5.1.7 on 2025-04-07 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_auto_20250407_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establishment',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email'),
        ),
    ]
